services:
  notifier-bot:
    build: .
    container_name: notifier-bot
    restart: unless-stopped
    init: true
    tty: true
    stdin_open: true
    volumes:
      - type: bind
        source: ./config
        target: /discordbot/config
      - /etc/localtime:/etc/localtime:ro